name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, json
        coverage: xdebug

    - name: Setup Project
      run: make setup

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Run formatter check (pint)
      run: ./vendor/bin/pint --test --preset psr12